# Generated by Django 4.0.6 on 2022-08-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angency', '0002_alter_agencyprofile_dl_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprofile',
            name='dl_avatar',
            field=models.CharField(blank=True, default='https://icon-icons.com/icon/avatar-people-person-black-hair-man-male-boy/120513', max_length=100),
        ),
    ]
