# Generated by Django 4.0.6 on 2022-09-18 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('voucher', '0002_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='order_detail',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='orders.orderdetail'),
            preserve_default=False,
        ),
    ]
