# Generated by Django 4.0.6 on 2022-10-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_voucher_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Price'), (1, 'Number')], default=0),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Reduce Price'), (1, 'Reduce Percent')], default=0),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='scope',
            field=models.IntegerField(choices=[(0, 'All'), (1, 'Special')], default=0),
        ),
    ]
