# Generated by Django 4.0.6 on 2022-11-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0013_remove_voucher_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
