# Generated by Django 4.0.6 on 2022-11-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0014_alter_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
