# Generated by Django 4.0.6 on 2022-09-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
