version: '3.10.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/bnShopApi/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=bnshop
volumes:
  postgres_data:
