# Generated by Django 4.0.6 on 2022-08-26 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_ten', models.CharField(max_length=1000)),
                ('sp_moTaSanPham', models.TextField()),
                ('sp_soLuong', models.BigIntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_tuNgay', models.DateField()),
                ('g_gia', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_OfType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeof', to='product.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productof', to='product.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctsp_tieuDe', models.CharField(max_length=100)),
                ('ctsp_noiDung', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='product.product')),
            ],
        ),
    ]
