# Generated by Django 4.0.6 on 2022-08-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Detail',
            new_name='ProductDetail',
        ),
        migrations.RenameModel(
            old_name='Product_OfType',
            new_name='ProductOfType',
        ),
        migrations.RenameModel(
            old_name='Product_Price',
            new_name='ProductPrice',
        ),
        migrations.RenameModel(
            old_name='Product_Type',
            new_name='ProductType',
        ),
    ]
