# Generated by Django 4.0.6 on 2022-09-08 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='g_tuNgay',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 8)),
        ),
    ]
