# Generated by Django 4.0.6 on 2022-09-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productprice_g_tungay'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
