# Generated by Django 4.0.6 on 2022-09-10 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productimage_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='g_tuNgay',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 10)),
        ),
    ]
