# Generated by Django 4.0.6 on 2022-09-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='time_visited',
        ),
    ]
