# Generated by Django 4.0.6 on 2022-09-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_users_time_visited'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('customer', 'agency')},
        ),
    ]
