# Generated by Django 4.0.6 on 2022-11-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_visit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_shipper',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=3000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipper', to='accounts.users')),
            ],
        ),
    ]
