# Generated by Django 4.0.6 on 2022-11-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_is_shipper_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_shipper',
            field=models.BooleanField(default=False),
        ),
    ]
