# Generated by Django 4.0.6 on 2022-12-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_agency_identify'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Product'), (2, 'Rating'), (3, 'Order')])),
            ],
        ),
        migrations.CreateModel(
            name='SubAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_agency', to='accounts.agency')),
                ('role', models.ManyToManyField(related_name='sub_agency', to='accounts.roleagency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_agency', to='accounts.users')),
            ],
        ),
    ]
