# Generated by Django 4.0.6 on 2022-12-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_roleagency_subagency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleagency',
            old_name='role',
            new_name='rolesub',
        ),
        migrations.RenameField(
            model_name='subagency',
            old_name='role',
            new_name='rolesub',
        ),
    ]
