# Generated by Django 4.0.6 on 2022-09-18 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('type', models.IntegerField(blank=True, default=2)),
                ('rate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='rating.rate')),
            ],
        ),
    ]
