# Generated by Django 4.0.6 on 2022-11-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
