# Generated by Django 4.0.6 on 2022-11-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_rate_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
