# Generated by Django 4.0.6 on 2022-09-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='origin',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='origin_brand',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
