# Generated by Django 4.0.6 on 2022-09-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_origin_alter_brand_origin_brand_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('origin', 'origin_brand')},
        ),
    ]
