# Generated by Django 4.0.6 on 2022-09-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('origin', 'origin_brand', 'name')},
        ),
    ]
