# Generated by Django 4.0.6 on 2022-10-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_brand_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='products.product'),
        ),
    ]
