# Generated by Django 4.0.6 on 2022-11-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_quantity_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_image',
            field=models.CharField(max_length=30000),
        ),
    ]
