# Generated by Django 4.0.6 on 2022-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='change_num',
            field=models.IntegerField(null=True),
        ),
    ]
