# Generated by Django 4.0.6 on 2022-11-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_quantity_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.CharField(max_length=3000),
        ),
    ]
