# Generated by Django 4.0.6 on 2022-10-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='detail',
            new_name='order_detail',
        ),
    ]
