# Generated by Django 4.0.6 on 2022-10-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_address_is_delete'),
        ('orders', '0003_rename_detail_order_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='address.address'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='orders.payment'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
