# Generated by Django 4.0.6 on 2022-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cancel_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('1', 'Waiting for confirm'), ('2', 'Agency confirmed'), ('3', 'Delivering'), ('4', 'Cancel'), ('5', 'Received')], max_length=100),
        ),
    ]
