# Generated by Django 4.0.6 on 2022-11-15 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderdetail_shipper'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusShippingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substatus', models.IntegerField(choices=[('0', 'Delivery success'), ('1', 'Delivery unsuccess')])),
                ('note', models.TextField()),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_shipping', to='orders.orderdetail')),
            ],
        ),
    ]
