# Generated by Django 4.0.6 on 2022-11-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_is_shipper_shipper'),
        ('orders', '0010_statusshippingnote_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='accounts.customer'),
            preserve_default=False,
        ),
    ]
