# Generated by Django 4.0.6 on 2022-11-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_address_is_delete'),
        ('orders', '0011_orderdetail_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='address.address'),
        ),
    ]
