# Generated by Django 4.0.6 on 2022-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderdetail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusshippingnote',
            name='substatus',
            field=models.IntegerField(choices=[('0', 'Delivery success'), ('1', 'Delivery unsuccess'), ('2', 'Customer cancel')]),
        ),
    ]
