# Generated by Django 4.0.6 on 2022-11-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_is_shipper'),
        ('orders', '0013_alter_statusshippingnote_substatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='accounts.agency'),
        ),
    ]
