# Generated by Django 4.0.6 on 2022-12-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderdetail_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusshippingnote',
            name='image',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='statusshippingnote',
            name='substatus',
            field=models.IntegerField(choices=[(0, 'Delivery success'), (1, 'Delivery unsuccess'), (2, 'Customer cancel')]),
        ),
    ]
