# Generated by Django 4.0.6 on 2022-08-23 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kh_ho', models.CharField(max_length=60)),
                ('kh_ten', models.CharField(max_length=60)),
                ('kh_avatar', models.CharField(default='https://icon-icons.com/icon/avatar-people-person-black-hair-man-male-boy/120513', max_length=100)),
                ('kh_email', models.EmailField(max_length=254, null=True)),
                ('kh_sdt', models.CharField(max_length=11)),
                ('kh_ngay_sinh', models.DateField()),
                ('kh_gioi_tinh', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cus_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
