# Generated by Django 4.0.6 on 2022-08-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerprofile_kh_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='kh_avatar',
            field=models.CharField(blank=True, default='https://icon-icons.com/icon/avatar-people-person-black-hair-man-male-boy/120513', max_length=100),
        ),
    ]
